import React, { useRouter } from "next/router";
import { skuSchema, type ISku } from "~/components/validation/route";
import ErrorPage from "next/error";
import Head from "next/head";
import Image from "next/image";
import Header from "~/components/Header";
import Footer from "~/components/Footer";
import type { IProductDetail } from "~/components/validation/productDetail";
import { getSku, getProductData } from "~/lib/product";

//ISR this page for better SEO and performance

const ProductPage = ({
  productData,
}: {
  productData: IProductDetail["detail"]["data"]["catalog"]["product"];
}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col bg-base-200">
        <div className="fixed top-0 z-50 flex w-full justify-start px-4 py-3">
          <Header />
        </div>
        <div className="relative mx-4 mt-24 flex flex-col justify-center gap-6">
          <div className="flex w-full overflow-hidden rounded-xl shadow-2xl">
            <div className="hero bg-base-100">
              <div className="hero-content w-full max-w-none flex-col-reverse px-0 py-0 md:flex-row">
                <div className="relative left-0 h-[35rem] w-full overflow-hidden">
                  {productData ? (
                    <Image
                      alt={productData?.media[0]?.altText || "banner"}
                      src={productData?.media[0]?.fullUrl || "/Banner1.png"}
                      fill
                      className="z-10 object-cover"
                    />
                  ) : (
                    <progress className="progress w-56"></progress>
                  )}
                </div>
                <div className="px-10 py-10">
                  <h1 className="w-1/2 whitespace-nowrap text-5xl font-bold">
                    {productData?.name}
                  </h1>
                  <p className="py-6">{productData?.description}</p>
                  <button className="btn-primary btn">Explore</button>
                </div>
              </div>
            </div>
          </div>
          <div className="flex w-full flex-col  items-center justify-center rounded-xl bg-base-100 drop-shadow-lg">
            <h1 className="my-10 text-4xl font-bold ">New Arrivals</h1>
            <div
              tabIndex={0}
              className="collapse-arrow rounded-box collapse border border-base-300 bg-base-100"
            >
              <div className="collapse-title text-xl font-medium">
                Product Info
              </div>
              <div className="collapse-content">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                </p>
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export async function getStaticPaths() {
  const paths = await getSku();
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }: { params: { sku: string } }) {
  const productData = await getProductData(params.sku);

  return {
    props: {
      productData,
      revalidate: 60,
    },
  };
}
export default ProductPage;
