import Header from "../components/Header";
import Footer from "../components/Footer";
// import Image from "next/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import { api } from "~/utils/api";

// this page will be cliant side rendered

const Cart = () => {
  const result = api.cart.view.useQuery();
  // const [data, setData] = useState();
  // useEffect(() => {
  //   const data = result.data?.detail.cart_list.map((item) => {
  //     return (
  //       <tr key={item.sku}>
  //       <td>
  //         <div className="flex items-center space-x-3">
  //           <div className="avatar">
  //             <div className="mask mask-squircle h-12 w-12">
  //               <img
  //                 src={item.fullUrl}
  //                 alt={item.name}
  //               />
  //             </div>
  //           </div>
  //           <div>
  //             <div className="font-bold">{item.color}</div>
  //             <div className="text-sm opacity-50">{item.size}</div>
  //             <div className="text-sm opacity-50">{item.discountedPrice}</div>
  //           </div>
  //         </div>
  //       </td>
  //       <td>{item.qty}</td>
  //       </tr>
  //     );
  //   });
  // }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col bg-base-200">
        <div className="fixed top-0 z-50 flex w-full justify-start px-4 py-3">
          <Header />
        </div>
        <div className="relative mx-4 mt-24 flex flex-col justify-center gap-6">
          <div className="flex w-full flex-col overflow-hidden rounded-xl bg-base-100 shadow-2xl">
            <h1 className="mx-10 my-10 text-4xl font-bold ">Cart</h1>
            <div className="mb-10 overflow-x-auto rounded-none md:rounded-xl md:mx-10 md:drop-shadow-xl">
              <table className="table-compact table rounded-none w-full md:table-normal">
                {/* head */}
                <thead>
                  <tr>
                    <th>Items</th>
                    {/* <th>Options</th> */}
                    <th>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {/* row 1 */}
                  {result &&
                    result.data?.detail.cart_list.map((item) => {
                      return (
                        <tr key={item.sku}>
                          <td>
                            <div className="flex items-center space-x-3">
                              <div className="avatar">
                                <div className="mask mask-squircle h-16 w-16">
                                  <img src={item.fullUrl} alt={item.name} />
                                </div>
                              </div>
                              <div>
                                <div className="font-bold">{item.name}</div>
                                <div className="text-sm opacity-50">
                                  {item.color}
                                </div>
                                <div className="text-sm opacity-50">
                                  {item.size}
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="">
                            {item.qty}{' x '}
                            <div className={`opacity-50 inline-flex ${item.discountedPrice < item.price ? 'line-through decoration-error': ''}`}>
                              {item.discountedPrice}
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                </tbody>
              </table>
            </div>
          </div>
          {/* <div className="flex w-full flex-col  items-center justify-center rounded-xl bg-base-100 drop-shadow-lg">
              <h1 className="my-10 text-4xl font-bold ">New Arrivals</h1>
              <div className="w-full overflow-scroll">
                <Collection response={res} />
              </div>
            </div> */}
        </div>
        <Footer />
      </main>
    </>
  );
};
export default Cart;
