import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { Container } from "postcss";
import Header from "~/components/Header";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-screen flex-col bg-base-200">
        <div className="fixed top-0 z-50 flex w-full justify-start px-4 py-3">
          <Header />
        </div>
        <div className="relative mx-4 mt-24 flex flex-col justify-center gap-6">
          <div className="flex h-[35rem] w-full overflow-hidden rounded-xl drop-shadow-lg">
            <div className="hero min-h-screen bg-base-200">
              <div className="hero-content flex-col lg:flex-row">
                {/* <img
                  src="/Banner1.png"
                  className="max-w-sm rounded-lg shadow-2xl"
                /> */}
                <div className=" w-[24rem] h-full rounded-lg shadow-2xl"> <Image
                alt="banner"
                src="/Banner1.png"
                fill
                className="z-0 object-contain object-right-top"
              /></div>
                <div>
                  <h1 className="text-5xl font-bold">Box Office News!</h1>
                  <p className="py-6">
                    Provident cupiditate voluptatem et in. Quaerat fugiat ut
                    assumenda excepturi exercitationem quasi. In deleniti eaque
                    aut repudiandae et a id nisi.
                  </p>
                  <button className="btn-primary btn">Get Started</button>
                </div>
              </div>
            </div>
            {/* <div className="z-0">
              <Image
                alt="banner"
                src="/Banner1.png"
                fill
                className="z-0 object-cover object-right-top"
              />
            </div>
            <div className="absolute right-0 top-1/2 z-10 text-black align-middle">
              <div className="flex flex-col justify-center mr-28 text-5xl font-bold text-primary-content align-middle">HappyKids  </div>
            </div> */}
          </div>
          <div className="flex w-full overflow-hidden rounded-xl bg-base-100 drop-shadow-lg">
            <h1 className="h1">Store Collections</h1>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
